name: Robot Framework Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
   steps:
      - name: Checkout Repository
# run: echo Fazendo clone do repositorio na maquina virtual
        uses: actions/checkout@v4
     - name: Set up Python
# run: echo Instalação da versão 3.12 do Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
     - name: Install dependencies
        # run: echo Instalação das depedências do Projeto
        run: |
          pip install robotframework
          pip install robotframework-requests
     - name: Run Robot Framework tests
# run: echo Executando os testes de API do Robot
        run: |
          robot --outputdir results/ serverest/tests/
        # no lugar de serverest/tests coloca o caminho da pasta que vc vai usar, onde esta salvo os tests case, ela vai ser salva dentro de uma pasta results, com todos os reports 
      - name: Test Report
        # run: echo Salvando o Report dos Testes
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-report
          path: results/**